### PR TITLE
Update README.md for Pi-hole version 5+

### PR DESCRIPTION
**Pull request by robcmo**
* simplifies code.
* adds domains to custom.list which improves Pi-hole visibility.
* domains are displayed on Pi-hole webpage menu under "Local DNS Records".
* service no longer needs to be restarted.

### CODE REVIEW

**Comment by robcmo** [comment]
If you prefer, the first line can be removed as well. Up to you.
`cd~`

**Comment by urmum-69** [comment]
I think it would be better to use the following command
```sh
curl https://raw.githubusercontent.com/RiiConnect24/DNS-Server/master/dns_zones-hosts.txt >> /etc/pihole/custom.list
```
Does the same thing in one line, and doesn't save any file to disk.

**Comment by robcmo** [comment]
Good call! I didn't realize that appends, but tested and it does. I will resubmit code change.

**Comment by urmum-69** [comment]
change "commands" to "command" since there is only one now

**Comment by robcmo** [comment]
Should be all set, thanks @urmum-69!

**Pull request merged**
