### PR TITLE
Added missing domains for Mario Kart (NDS)

### PR DESCRIPTION
**Pull request by wuniversales**

### CODE REVIEW

**Comment by urmum-69** [comment]
This has already been done... #17

**Comment by 2secslater** [comment]
`dns_zones-hosts.txt` exists also, for dnsmasq/pi-hole users

**Comment by wuniversales** [comment]
> This has already been done... #15

Those URLs that I added do not exist, these (Apart from the previous ones) are also necessary to access in mario kart of nintendo ds

**Comment by Artuto** [comment]
Please modify both files in the same PR (#17).

**Comment by Artuto** [comment]
why did it dupe

**Comment by wuniversales** [comment]
I'm a git novice, that's why I did it in two ...

**Pull request closed without merging**
